name: BedWars2023Generator
version: 1.4v
main: com.abbas.bedWarws2023Gentrator.BedWars2023Generator
api-version: '1.13'
author: Abbas
description: An addon that rewards players with XP for collecting resources in BedWars2023.
depend:
  - BedWars2023
load: STARTUP
